package com.agency04.sbss.pizza;

public enum PizzaIngredient {
    FRENCH_FRIES, MOZZARELLA, SAUSAGE, TOMATO_SAUCE, HAM, ARTICHOKES, MUSHROOMS,
    OLIVES, SEAFOOD, OREGANO, PARMESAN, GORGONZOLA_CHEESE, ONIONS, TUNA, VARIOUS_VEGETABLES
}
